export const WEATHER_REQUEST = 'WEATHER_REQUEST';
export const WEATHER_SUCCESS = 'WEATHER_SUCCESS';
export const WEATHER_FAILURE = 'WEATHER_FAILURE';

export const CITY_NAME_CHANGE = 'CITY_NAME_CHANGE';